cybersecurity/StableCleaned/cybersecurity/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from ajax_select import urls as ajax_select_urls
from trainingPortal import views
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cybersecurity.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^admin/lookups/', include(ajax_select_urls)),
	url(r'^trainingPortal/forum/', include('pybb.urls', namespace='pybb')),
	url(r'^accounts/', include('allauth.urls')),
	url(r'^trainingPortal/', include('trainingPortal.urls')), #application
	url(r'^trainingPortal/test/', include('quiz.urls')),
	url(r'^trainingPortal/user/messages/', include('postman.urls')),
	url(r'^', include('cms.urls')),
	url(r'^ckeditor/', include('ckeditor.urls')),
	url(r'^tinymce/', include('tinymce.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cybersecurity/StableCleaned/externalapps/New folder/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
try:
    from django.conf.urls import patterns, include, url
except ImportError:
    from django.conf.urls.defaults import patterns, include, url

from pybb.feeds import LastPosts, LastTopics
from pybb.views import IndexView, CategoryView, ForumView, TopicView,\
    AddPostView, EditPostView, UserView, PostView, ProfileEditView,\
    DeletePostView, StickTopicView, UnstickTopicView, CloseTopicView,\
    OpenTopicView, ModeratePost, TopicPollVoteView, LatestTopicsView,\
    UserTopics, UserPosts, topic_cancel_poll_vote


urlpatterns = patterns('',
                       # Syndication feeds
                       url('^feeds/posts/$', LastPosts(), name='feed_posts'),
                       url('^feeds/topics/$', LastTopics(), name='feed_topics'),
                       )

urlpatterns += patterns('pybb.views',
                        # Index, Category, Forum
                        url('^$', IndexView.as_view(), name='index'),
                        url('^category/(?P<pk>\d+)/$', CategoryView.as_view(), name='category'),
                        url('^forum/(?P<pk>\d+)/$', ForumView.as_view(), name='forum'),

                        # User
                        url('^users/(?P<username>[^/]+)/$', UserView.as_view(), name='user'),
                        url('^block_user/([^/]+)/$', 'block_user', name='block_user'),
                        url('^unblock_user/([^/]+)/$', 'unblock_user', name='unblock_user'),
                        url(r'^users/(?P<username>[^/]+)/topics/$', UserTopics.as_view(), name='user_topics'),
                        url(r'^users/(?P<username>[^/]+)/posts/$', UserPosts.as_view(), name='user_posts'),

                        # Profile
                        url('^profile/edit/$', ProfileEditView.as_view(), name='edit_profile'),

                        # Topic
                        url('^topic/(?P<pk>\d+)/$', TopicView.as_view(), name='topic'),
                        url('^topic/(?P<pk>\d+)/stick/$', StickTopicView.as_view(), name='stick_topic'),
                        url('^topic/(?P<pk>\d+)/unstick/$', UnstickTopicView.as_view(), name='unstick_topic'),
                        url('^topic/(?P<pk>\d+)/close/$', CloseTopicView.as_view(), name='close_topic'),
                        url('^topic/(?P<pk>\d+)/open/$', OpenTopicView.as_view(), name='open_topic'),
                        url('^topic/(?P<pk>\d+)/poll_vote/$', TopicPollVoteView.as_view(), name='topic_poll_vote'),
                        url('^topic/(?P<pk>\d+)/cancel_poll_vote/$', topic_cancel_poll_vote, name='topic_cancel_poll_vote'),
                        url('^topic/latest/$', LatestTopicsView.as_view(), name='topic_latest'),

                        # Add topic/post
                        url('^forum/(?P<forum_id>\d+)/topic/add/$', AddPostView.as_view(), name='add_topic'),
                        url('^topic/(?P<topic_id>\d+)/post/add/$', AddPostView.as_view(), name='add_post'),

                        # Post
                        url('^post/(?P<pk>\d+)/$', PostView.as_view(), name='post'),
                        url('^post/(?P<pk>\d+)/edit/$', EditPostView.as_view(), name='edit_post'),
                        url('^post/(?P<pk>\d+)/delete/$', DeletePostView.as_view(), name='delete_post'),
                        url('^post/(?P<pk>\d+)/moderate/$', ModeratePost.as_view(), name='moderate_post'),

                        # Attachment
                        #url('^attachment/(\w+)/$', 'show_attachment', name='pybb_attachment'),

                        # Subscription
                        url('^subscription/topic/(\d+)/delete/$',
                            'delete_subscription', name='delete_subscription'),
                        url('^subscription/topic/(\d+)/add/$',
                            'add_subscription', name='add_subscription'),

                        # API
                        url('^api/post_ajax_preview/$', 'post_ajax_preview', name='post_ajax_preview'),

                        # Commands
                        url('^mark_all_as_read/$', 'mark_all_as_read', name='mark_all_as_read')
                        )

cybersecurity/StableCleaned/externalapps/pybb/urls.py
# Copyright: 2011, Grigoriy Petukhov
# Author: Grigoriy Petukhov (http://lorien.name)
# License: BSD
from django.conf.urls import patterns, url, include

from pybb import views
from pybb import feeds


urlpatterns = patterns('',
    # Syndication feeds
    url('^feed/all/post$', feeds.LatestPostFeed(), name='pybb_feed_post'),
    url('^feed/all/topic$', feeds.LatestTopicFeed(), name='pybb_feed_topic'),
    url('^feed/forum/tag/(\w+)/topic$', feeds.ForumByTagFeed(), name='pybb_feed_forum_bytag_topic'),
    url('^feed/forum/id/(\d+)/topic$', feeds.ForumByIdFeed(), name='pybb_feed_forum_byid_topic'),
)

urlpatterns += patterns('pybb.views',
    # Index, Category, Forum
    url('^$', 'index', name='pybb_index'),
    url('^category/(\d+)/$', 'category_details', name='pybb_category_details'),
    url('^forum/(\d+)/$', 'forum_details', name='pybb_forum_details'),

    # User
    url('^user/$', 'user_list', name='pybb_user_list'),
    url('^user/([^/]+)/$', 'user_details', name='pybb_user_details'),
    url('^user/([^/]+)/topics/$', 'user_details_topics', name='pybb_user_details_topics'),

    # Profile
    url('^profile/edit/$', 'profile_edit', name='pybb_profile_edit'),

    # Topic
    url('^topic/(\d+)/$', 'topic_details', name='pybb_topic_details'),
    url('^topic/(\d+)/stick/$', 'topic_stick', name='pybb_topic_stick'),
    url('^topic/(\d+)/unstick/$', 'topic_unstick', name='pybb_topic_unstick'),
    url('^topic/(\d+)/close/$', 'topic_close', name='pybb_topic_close'),
    url('^topic/(\d+)/open/$', 'topic_open', name='pybb_topic_open'),
    url('^topic/merge/$', 'topic_merge', name='pybb_topic_merge'),

    # Add topic/post
    url('^forum/(?P<forum_id>\d+)/topic/add/$', 'post_add',
        {'topic_id': None}, name='pybb_topic_add'),
    url('^topic/(?P<topic_id>\d+)/post/add/$', 'post_add',
        {'forum_id': None}, name='pybb_post_add'),

    # Post
    url('^post/(\d+)/$', 'post_details', name='pybb_post_details'),
    url('^post/(\d+)/edit/$', 'post_edit', name='pybb_post_edit'),
    url('^post/(\d+)/delete/$', 'post_delete', name='pybb_post_delete'),

    # Attachment
    url('^attachment/(\w+)/$', 'attachment_details', name='pybb_attachment_details'),

    # Subscription
    url('^subscription/topic/(\d+)/delete/$',
        'subscription_delete', name='pybb_subscription_delete'),
    url('^subscription/topic/(\d+)/add/$',
        'subscription_add', name='pybb_subscription_add'),

    # API
    url('^api/post_ajax_preview/$', 'post_ajax_preview', name='pybb_post_ajax_preview'),
)

cybersecurity/StableCleaned/templates/pybb/markup/bbcode_widget.html
{% load url from future %}
{% load i18n %}

{{ widget_output }}


<script type="text/javascript">
if(!window.pybb){
    window.pybb = {};
}
if(!window.pybb.get_markitup_settings){
    window.pybb.get_markitup_settings = function() {
        var mySettings = new Array();
        mySettings['previewParserPath'] = '{% url "pybb:post_ajax_preview" %}';
        mySettings['previewPosition'] = 'before';
        mySettings['resizeHandle'] = true;
        mySettings['markupSet'] = [
            {name:'{% trans "Bold" %}', key:'B', openWith:'[b]', closeWith:'[/b]'},
            {name:'{% trans "Italic" %}', key:'I', openWith:'[i]', closeWith:'[/i]'},
            {name:'{% trans "Underline" %}', key:'U', openWith:'[u]', closeWith:'[/u]'},
            {name:'{% trans "Stroke" %}', key:'S', openWith:'[s]', closeWith:'[/s]'},
            {separator:'---------------' },
            {name:'{% trans "Picture" %}', key:'P', replaceWith:'[img][![Url]!][/img]'},
            {name:'{% trans "Link" %}', key:'L', openWith:'[url=[![Url]!]]', closeWith:'[/url]', placeHolder:'{% trans "Your text to link here..." %}'},
            {separator:'---------------' },
            {name:'{% trans "Bulleted list" %}', openWith:'[list]\n', closeWith:'\n[/list]'},
            {name:'{% trans "Numeric list" %}', openWith:'[list=[![Starting number]!]]\n', closeWith:'\n[/list]'},
            {name:'{% trans "List item" %}', openWith:'[*] '},
            {separator:'---------------' },
            {name:'{% trans "Quotes" %}', openWith:'[quote]', closeWith:'[/quote]'},
            {name:'{% trans "Code" %}', openWith:'[code]', closeWith:'[/code]'},
            {separator:'---------------' },
            {name:'{% trans "Clean" %}', className:"clean", replaceWith:function(markitup) { return markitup.selection.replace(/\[(.*?)\]/g, "") } },
            {name:'{% trans "Preview" %}', className:"preview", call:'preview' }
        ];
        return mySettings ;
    };
}
</script>

cybersecurity/StableCleaned/templates/pybb/markup/markdown_widget.html
{% load url from future %}
{% load i18n %}

{{ widget_output }}


<script type="text/javascript">
if(!window.pybb){
    window.pybb = {};
}
if(!window.pybb.get_markitup_settings){
    window.pybb.get_markitup_settings = function() {
        var mySettings = new Array();
        mySettings['previewParserPath'] = '{% url "pybb:post_ajax_preview" %}';
        mySettings['previewPosition'] = 'before';
        mySettings['resizeHandle'] = true;
        mySettings['markupSet'] = [
            {name:'{% trans "First Level Heading" %}', key:'1', placeHolder:'{% trans "Your title here..." %}', closeWith:function(markItUp) { return miu.markdownTitle(markItUp, '=') } },
            {name:'{% trans "Second Level Heading" %}', key:'2', placeHolder:'{% trans "Your title here..." %}', closeWith:function(markItUp) { return miu.markdownTitle(markItUp, '-') } },
            {name:'{% trans "Heading 3" %}', key:'3', openWith:'### ', placeHolder:'{% trans "Your title here..." %}' },
            {name:'{% trans "Heading 4" %}', key:'4', openWith:'#### ', placeHolder:'{% trans "Your title here..." %}' },
            {name:'{% trans "Heading 5" %}', key:'5', openWith:'##### ', placeHolder:'{% trans "Your title here..." %}' },
            {name:'{% trans "Heading 6" %}', key:'6', openWith:'###### ', placeHolder:'{% trans "Your title here..." %}' },
            {separator:'---------------' },        
            {name:'{% trans "Bold" %}', key:'B', openWith:'**', closeWith:'**'},
            {name:'{% trans "Italic" %}', key:'I', openWith:'_', closeWith:'_'},
            {separator:'---------------' },
            {name:'{% trans "Bulleted List" %}', openWith:'- ' },
            {name:'{% trans "Numeric List" %}', openWith:function(markItUp) {
                return markItUp.line+'. ';
            }},
            {separator:'---------------' },
            {name:'{% trans "Picture" %}', key:'P', replaceWith:'![[![Alternative text]!]]([![Url:!:http://]!] "[![Title]!]")'},
            {name:'{% trans "Link" %}', key:'L', openWith:'[', closeWith:']([![Url:!:http://]!] "[![Title]!]")', placeHolder:'{% trans "Your text to link here..." %}' },
            {separator:'---------------'},    
            {name:'{% trans "Quotes" %}', openWith:'> '},
            {name:'{% trans "Code Block / Code" %}', openWith:'(!(\t|!|`)!)', closeWith:'(!(`)!)'},
            {separator:'---------------'},
            {name:'{% trans "Preview" %}', call:'preview', className:"preview"}
        ];
        return mySettings ;
    };
}
</script>